# Generated by Django 5.1.7 on 2025-03-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Crearted_at',
            new_name='created_at',
        ),
    ]
