# Generated by Django 5.1.7 on 2025-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/default-profile.jpg', upload_to='profile_picture/'),
        ),
    ]
